# Generated by Django 4.0 on 2024-01-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='create_datetime',
            new_name='created_datetime',
        ),
    ]
