# Generated by Django 4.0 on 2025-02-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatmessage_options_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, default='images/group_default.png', null=True, upload_to='images/account/2025-02-22 12:45:12.488621/'),
        ),
    ]
