# Generated by Django 4.0 on 2025-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(blank=True, default='images/group_default.png', null=True, upload_to='images/account/2025-02-22 13:52:27.599269/'),
        ),
    ]
