# Generated by Django 4.0 on 2024-06-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_datetime']},
        ),
    ]
