# Generated by Django 4.0 on 2024-01-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_created_datetime_comment_modified_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
    ]
