# Generated by Django 4.0 on 2024-05-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_datetime',)},
        ),
    ]
