name: Django CI/CD Pipeline
'on':
    # push code and github action trigger with manually 
    # workflow_dispatch:
    # push or pull request github action trigger automatically 	
    push:
        branches: [main]  # Adjust the branch name as needed
    # pull_request:
    #     branches: [main]  # Adjust the branch name as needed
jobs:
  
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r blog/requirements.txt
      - name: Run tests
        run: python blog/manage.py test
  deploy:
    name: Deploy to EC2 on main branch push
    # needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Server 1
        run: |
            ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@13.202.67.148 
            echo "Hello krishna"
        env:
           ACTIONS_RUNNER_DEBUG: false
