name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  pull_request:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r blog/requirements.txt

      - name: Run tests
        run: python manage.py test

  deploy:
    name: Deploy to AWS
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: project setup in ci/c
        run : echo "project setup run ci/ci"
